### ISSUE TITLE
Is 1.21 planned

### ISSUE THREAD

**Issue by HatTrkPatrk** [eclipseisoffline/modifyplayerdata#1]
Hi, I'm making preparations to setup a 1.21 SMP Fabric server for someone and I'm going through their requested modlist to see if support is planned.

Not asking per se for a release date/timetable but I do want to ask if a 1.21 version of this mod is at least planned. Thank you! (And sorry for being That Guy™ asking about versions lol)

**Comment by eclipseisoffline** [comment]
Hi, 1.21 support is definitely planned. As 1.21 pre-releases have started releasing and 1.21 is releasing in 2 weeks, I plan to start updating my mods for the pre-releases in the coming weeks. A 1.21 build will be up on Modrinth up to a few days after 1.21's release at most (probably one day, but there may be delays).
